#let undergraduate_profile = (
  id: "undergraduate",
  label: "SUSTech Undergraduate Thesis",
  info_zh: (
    clc: "CLC",
    thesis_id: "20260405",
    confidentiality_level: "公开",
    udc: "UDC",
    title: ("基于 Typst 的", "南方科技大学毕业论文模板"),
    subtitle: "v0.1.0",
    author: "咕桃",
    student_id: "32123432",
    department: "计算机科学与工程系",
    major: "计算机科学与技术",
    supervisor: "南小科",
    submit_date: datetime.today(),
  ),
  info_en: (
    clc: "CLC",
    thesis_id: "20260405",
    udc: "UDC",
    title: ("Graduation Thesis Template", "Based on Typst"),
    subtitle: "v0.1.0",
    author: "GuTao",
    student_id: "32123432",
    department: "Computer Science and Engineering",
    major: "Computer Science and Technology",
    supervisor: "XiaoKe Nan",
    submit_date: datetime.today(),
  ),
  options: (
    bibliography_style: "numeric",
    bibliography_standard: "2015",
    bibliography_full: false,
    bibliography_show_url: true,
    bibliography_show_doi: true,
    bibliography_show_accessed: true,
    include_en_cover: true,
    include_en_declaration: true,
    include_list_of_figures: false,
    include_list_of_tables: false,
    prefer_en_header: false,
    abstract_en_first: false,
    list_of_figures_show_both: true,
    list_of_tables_show_both: true,
    references_show_both: true,
    appendix_show_both: true,
    acknowledgement_show_both: true,
  ),
  page_numbering: (
    preface: "I",
    mainmatter: "1",
  ),
)
